# Generated by Django 5.0 on 2024-11-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
